### PR TITLE
RFC26_RedesignUI

### PR DESCRIPTION
**Pull request by Ahelsamahy**
The user can connect to the robot with their mobile device or a device in a controlling room. They see the robot's web application in order to control the robot's functions. When the user connects to the web app, they will see the User Interface (UI) of the app. There are two different UI depending on which device are you using, Mobile Controller (MC) and normal Controller (NC).

The current UI we have wasn't made while considering making it intuitive as much as possible for the user. This feature will change the UI in order to make it simple for the user to understand it.

### CODE REVIEW

**Comment by Ahelsamahy** [comment]
I stopped showing the stream for now on the normal UI. If you want to see the stream and a stable release, please pull https://github.com/MWLCDev/BYODR/pull/34/commits/49fb05734db2a8c1cbfba6744676b6058891553f

**Comment by Ahelsamahy** [comment]
I changed in `index.js` to remove all the exports from it. All vanilla JS classes will go through it, then be sent to other classes, if needed. I will remove the concept of exporting functions (`teleop_screen` is one of them) and instead make them as one class

**Comment by Ahelsamahy** [comment]
Today's test
- Iframe needs to be hidden when navigating from different modes (UI)
- Need to implement dead zone feature (software)
- Need to stop the streams when on mobile phone (software)
- Need to stop `shoe_image` command from fol when exiting fol. Only generate the images when on fol mode page (software)

**Comment by Ahelsamahy** [comment]
These are naming conventions that I will implement in the course of writing the code in this repo. Why? Because when i try to find a variable with bulk searching (`shift+cmd+f`) I would come across a dom element tag or a python va, so I decided to have a standard rule to follow. I will try to make workflow tests later to enforce these rules

## Python follows the PEP 8 style guide for naming conventions

- **Classes**: Use the CapWords convention (also known as PascalCase). Example: `MyClass`
- **Functions**: Use lowercase with words separated by underscores(snake_case). Example: `my_function`
- **Variables**: Use lowercase with words separated by underscores. Example: `my_variable`
- **Constants**: Use all uppercase with words separated by underscores. Example: `MY_CONSTANT`
- **File Names**: Use lowercase with words separated by underscores. Example: `my_module.py`, `data_processor.py`

## JavaScript (Vanilla and jQuery)

- **Classes**: Use PascalCase (same as CapWords). Example: `MyClass`
- **Functions**: Use (camelCase). Example: `myFunction`
- **Variables**:
  - Use camelCase for regular variables. Example: `myVariable`
  - Use UPPER_CASE for constants. Example: `MY_CONSTANT`
  - jQuery Variables: It's a common practice to prefix jQuery object variables with a $. Example: `$myElement`
- **File Names**: Use lowercase with words separated by hyphens (kebab-case). Example: `my-script.js`, `user-profile.js`

## CSS

- **Classes**: Use lowercase and separate words with hyphens. Example: `.my-class`
- **IDs**: Same as classes, though IDs should be used sparingly. Example: `#my-id`
- **Variables**: (If using CSS preprocessors like Sass or native CSS variables) Use lowercase and separate words with hyphens. Example: `--my-variable`
- **File Names**: Use lowercase with words separated by hyphens (kebab-case). Example: `styles.css`, `layout-grid.css`

## HTML

- **IDs**: Use lowercase and separate words with hyphens. Example: `id="my-id"`
- **Classes**: Follow the same style as in CSS. Example: `class="my-class"`
- **File Names**: Use lowercase with words separated by hyphens (kebab-case). Example: `index.html`, `about-us.html`

**Comment by Ahelsamahy** [comment]
This branch can be merged into master with few bugs into consideration:
1. The streams on normal UI need to be refreshed when going from any settings menu, to the manual mode again. A work around would be to refresh the page.
2. If the user switch from settings menu to one of the features immediately without going to the manual mode first (to start the streams) the streams won't show. To overcome this, the user needs to go to manual mode, refresh the page then go to the feature.

## Extra things I did that were not in the Figma design
- Added dark theme to the mobile UI even though it wasn't in the design.
- Added responsive designs on big screens (in case of a remote monitor) for normal UI
- Made the responsive area of the mobile UI take the whole width of the screen.
- There was a last minute change on the design to add a second "view" for the cameras. This view has the two cameras next to each others in the main view, instead of Picture-In-Picture (PIP) that we had in the old UI. To not make this change opinionated on the user, I added a switch between the normal view (box view) and the PIP. It can be found in the advanced settings menu

It is worth mentioning that there are some things I had them done, without my opinion in them, like having fixed features list in the nav bar even though some of these features do not work on all UI. For example, following feature should be only working mobile phone, but it is on the nav bar on the normal UI. The nav button itself won't make any changes but it is there for consistency in the design.

I'm planning to come back to this feature later, but after I finish [GPIO](https://github.com/MWLCDev/BYODR/pull/33) branch as it has higher priority

**Review by MWLCDev — APPROVED** [review]
This branch will add also following feature, which has its own branch that isn't finished yet. Further improvements related to Following feature, will be merged into master branch as the base for it will be there

**Pull request merged**
